version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installiere ssh und aws-cli falls nötig"
      - apt-get update && apt-get install -y openssh-client awscli


  pre_build:
    commands:
      - echo "Lese privaten SSH-Schlüssel aus SSM"
      - mkdir -p ~/.ssh
      - aws ssm get-parameter --name "/werbeinsel/ssh_private_key" --with-decryption --query "Parameter.Value" --output text > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - |
        echo "Host lightsail
        HostName 3.126.252.21
        User deploy
        IdentityFile ~/.ssh/id_rsa
        StrictHostKeyChecking=no" > ~/.ssh/config


  build:
    commands:
      - echo "Erstelle Deploy-Archiv mit Themes & Plugins"
      - tar czf deploy-package.tar.gz wp-content/themes/wi-theme wp-content/plugins/wi-forms wp-content/plugins/testplugin
      - scp -i ~/.ssh/id_rsa deploy-package.tar.gz lightsail:/home/bitnami/
      - ssh lightsail "
          tar xzf /home/bitnami/deploy-package.tar.gz -C /opt/bitnami/wordpress &&
          rm /home/bitnami/deploy-package.tar.gz &&
          sudo /opt/bitnami/ctlscript.sh restart apache
        "